/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cn.com.apvisa.apvisamall;

public final class R {
    public static final class anim {
        public static final int loading_img_small=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int money_item_back=0x7f050003;
        public static final int translucent_background=0x7f050002;
        public static final int transparency=0x7f050000;
        public static final int white=0x7f050001;
    }
    public static final class dimen {
        /** 
         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
    }
    public static final class drawable {
        public static final int ap_bank=0x7f020000;
        public static final int ap_bank_bg=0x7f020001;
        public static final int ap_beijing=0x7f020002;
        public static final int ap_bg=0x7f020003;
        public static final int ap_button_03=0x7f020004;
        public static final int ap_button_03_f=0x7f020005;
        public static final int ap_cadr=0x7f020006;
        public static final int ap_cadr_bg=0x7f020007;
        public static final int ap_card_line=0x7f020008;
        public static final int ap_close=0x7f020009;
        public static final int ap_edit_bg=0x7f02000a;
        public static final int ap_gold=0x7f02000b;
        public static final int ap_login_btn_selector=0x7f02000c;
        public static final int ap_mobifone=0x7f02000d;
        public static final int ap_mobifone_bg=0x7f02000e;
        public static final int ap_selector_bank_image=0x7f02000f;
        public static final int ap_selector_card_image=0x7f020010;
        public static final int ap_selector_imageview_background=0x7f020011;
        public static final int ap_selector_item_background=0x7f020012;
        public static final int ap_selector_mobifone_image=0x7f020013;
        public static final int ap_selector_sms_image=0x7f020014;
        public static final int ap_selector_smsgridview_item_background=0x7f020015;
        public static final int ap_selector_viettel_image=0x7f020016;
        public static final int ap_selector_vinaphone_image=0x7f020017;
        public static final int ap_sms=0x7f020018;
        public static final int ap_sms_bg=0x7f020019;
        public static final int ap_sms_item_bg=0x7f02001a;
        public static final int ap_sms_item_bg_press=0x7f02001b;
        public static final int ap_sms_money_bg=0x7f02001c;
        public static final int ap_spinner_1=0x7f02001d;
        public static final int ap_viettel=0x7f02001e;
        public static final int ap_viettel_bg=0x7f02001f;
        public static final int ap_vinaphone=0x7f020020;
        public static final int ap_vinaphone_bg=0x7f020021;
        public static final int black=0x7f02002d;
        public static final int blue=0x7f020029;
        public static final int cyan=0x7f02002c;
        public static final int darkgray=0x7f020023;
        public static final int drawable_8f8f8f=0x7f020033;
        public static final int drawable_e9e9e9=0x7f020031;
        public static final int drawable_f9f9f9=0x7f020032;
        public static final int gray=0x7f02002a;
        public static final int gray_bg=0x7f02002f;
        public static final int gray_black=0x7f020030;
        public static final int green=0x7f020025;
        public static final int ic_launcher=0x7f020022;
        public static final int lightgray=0x7f020026;
        public static final int magenta=0x7f02002b;
        public static final int red=0x7f020024;
        public static final int transparency=0x7f020027;
        public static final int white=0x7f02002e;
        public static final int yellow=0x7f020028;
    }
    public static final class id {
        public static final int action_settings=0x7f0a001b;
        public static final int amount=0x7f0a0016;
        public static final int amount_num=0x7f0a000c;
        public static final int aptest=0x7f0a001a;
        public static final int bank=0x7f0a0005;
        public static final int button_first=0x7f0a0015;
        public static final int card=0x7f0a0003;
        public static final int card_img=0x7f0a000b;
        public static final int card_money=0x7f0a000a;
        public static final int cardname=0x7f0a000d;
        public static final int close=0x7f0a0001;
        public static final int edit_pin=0x7f0a0013;
        public static final int edit_serial=0x7f0a0014;
        public static final int imageView1=0x7f0a0018;
        public static final int linearLayout1=0x7f0a0002;
        public static final int linearLayout2=0x7f0a0006;
        public static final int ll_parent=0x7f0a0000;
        public static final int loading=0x7f0a0009;
        public static final int mobifone=0x7f0a0011;
        public static final int money=0x7f0a000e;
        public static final int money_listview=0x7f0a000f;
        public static final int pay_img=0x7f0a0017;
        public static final int payname=0x7f0a0019;
        public static final int sms=0x7f0a0004;
        public static final int sms_gridview=0x7f0a0007;
        public static final int viettel=0x7f0a0010;
        public static final int vinaphone=0x7f0a0012;
        public static final int webView=0x7f0a0008;
    }
    public static final class layout {
        public static final int ap_appay_main=0x7f030000;
        public static final int ap_bank=0x7f030001;
        public static final int ap_card_money_list_item=0x7f030002;
        public static final int ap_home=0x7f030003;
        public static final int ap_item_card_type=0x7f030004;
        public static final int ap_loading_foot=0x7f030005;
        public static final int ap_main=0x7f030006;
        public static final int ap_pay=0x7f030007;
        public static final int ap_sms_gridview_item=0x7f030008;
        public static final int ap_sms_money_item=0x7f030009;
        public static final int ap_smspay=0x7f03000a;
        public static final int ap_test=0x7f03000b;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class string {
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int bottom_tab_bank=0x7f070005;
        public static final int bottom_tab_card=0x7f070003;
        public static final int bottom_tab_know=0x7f070006;
        public static final int bottom_tab_my=0x7f070008;
        public static final int bottom_tab_sms=0x7f070004;
        public static final int bottom_tab_wantknow=0x7f070007;
        public static final int hello_world=0x7f070002;
    }
    public static final class style {
        /** 
        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080001;
        public static final int translucent=0x7f080000;
    }
}
